### ISSUE TITLE
SQL Server Support

### ISSUE THREAD

**Issue by tmeacham** [mariodavid/cuba-component-data-import#100]
Any chance of adding support for SQL Server? It seems all the other major DMBS are covered.

**Comment by mariodavid** [comment]
hi,

currently mainly PostgreSQL and MySQL are supported. The reason is that in this point of development the data model changes quite often. Once the domain model has settled down a little bit, I will cover all major DBMS including MSSQL (when I find out how to run it in a docker container properly).

Until then, if you use CUBA studio, it will generate the db scripts directly in your application if the app component does not provide scripts for your used DBMS.

Bye
Mario

**Comment by genthalili** [comment]
True! If using with CUBA studio, it works as well with MSSQL, not tested yet with Oracle.

**Comment by sergeev-ms** [comment]
Hi, @mariodavid. 
It`s still not possible to add ms sql support?
