### ISSUE TITLE
Error updating own model

### ISSUE THREAD

**Issue by innovaringenieria** [mariodavid/cuba-component-data-import#119]
Every time I try to update my model I get the following error;

![image](https://user-images.githubusercontent.com/22368175/42702696-e31f8176-868f-11e8-8782-d62733a7cf24.png)

The detail is that I remove the component, update my model, then install it and everything works correctly.
I have verified the changes that indicate that the component must do but it is applied correctly. What I can do? or just use the component at the end of the development?

**Comment by mariodavid** [comment]
Hi,

since 0.4.0 `dynamicAttribute` is no longer available (see https://github.com/mariodavid/cuba-component-data-import/blob/master/CHANGELOG.md#040---26052018)

depending on which version you are and which version you came from, things might happen, that result in such a scenario.

> I have verified the changes that indicate that the component must do but it is applied correctly.

What do you mean?

> What I can do? or just use the component at the end of the development?

At the end of the development of the app component or the end of your app development? I think neither is necessary, although the app component has (especially in 0.2.0 - 0.4.0) in a pretty early state in terms of entity modeling. So - when using it in this time you have to be aware that a lot of stuff can change.

**Comment by innovaringenieria** [comment]
Hi @mariodavid, I understand everything you tell me, what I want to say is that it is rare that if I modify my data model using the component I always generate that error. I always desistalo the component, update my data model and again install the component in this way does not generate that error. I hope you have made me understand.

**Comment by mariodavid** [comment]
hi,

i'm not really sure how I can help you with that. It seems you used an old version of the data-import component, then updated it and now did not apply the DB migration scripts. This might happen from time to time as I said especially in the early stage of this app component. However, I do not expect major changes in the DB model (incompatible ones at least).

Is there anything I can help you with - otherwise I will close this issue here.
