### ISSUE TITLE
0.3.0 AttributeBindRequest not found

### ISSUE THREAD

**Issue by genthalili** [mariodavid/cuba-component-data-import#72]
`IllegalStateException: No valid Attribute binder for AttributeBindRequest: de.diedavids.cuba.dataimport.binding.AttributeBindRequest@1ffc1404 found
`
Since I upgraded to 0.3.0

**Comment by mariodavid** [comment]
Hi,

in order to help you properly, you have to provide (as I said before) at least the log files and better an example application with an example import file as well as your configuration. The more information I have from you the more likely it is that I can help you faster (or at all in this case).

Bye
Mario

**Comment by genthalili** [comment]
This was caused by setting wrong attribute name, since the attribute match is cases sensitive.
This can be avoid by creating a lookup-list on every Entity attribute matching all possible attributes, so to help the enduser not to make mistakes.
I'll try do implement this, but first I need to get familiar with groovy :)

**Comment by mariodavid** [comment]
you are absolutely right. The UI is not the desired state in fact. The task you described is defined in #24 .

It is a little bit problematic though, especially when the dynamic attributes should be also supported -  but doable.

Bye
Mario
