### ISSUE TITLE
import component into my project for developement

### ISSUE THREAD

**Issue by genthalili** [mariodavid/cuba-component-data-import#73]
Hi @mariodavid,

I'm trying to get the component side to side with my project : 
<img width="363" alt="screen shot 2018-05-11 at 12 00 44" src="https://user-images.githubusercontent.com/3913876/39919171-1e1c3980-5513-11e8-845f-e3abd1392d5e.png">

The idea is to use data-import component inside my app and be able to develop in live the component.

How did you do it ? Could you help my with this?

**Comment by mariodavid** [comment]
hi,

what do you mean by "develop in live the component"?

If you mean you want to change the source code of the app component and then use them in your application then you have to do a `./gradlew install` in the app component and after that reload the app in studio so that it will pick up the latest `0.4.0-SNAPSHOT` changes.

Directly changing the code is only possible if you override some Spring beans from the app component and then replace functionality in it.

Bye
Mario

**Comment by genthalili** [comment]
I agreee with debuggin only, but what if I fould the issue and then I want to fix the code.
Should I stop and then again restart the app after doing the `./gradlew install` on the component?

**Comment by mariodavid** [comment]
This is the only way I'm aware of - yes.

I'll close this for now since it has nothing to do with the app component in itself.
